import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BUSINESS } from './config/business'
import { services, industries, processSteps, why } from './data/siteData.jsx'
import './styles.css'

const nav = [['Home','/'],['Solutions','/#solutions'],['How It Works','/#process'],['Industries','/#industries'],['About','/#about'],['Contact','/#contact']]
function Logo(){return <a className="logo" href="/"><span className="mark">A</span><span>Autonestix</span></a>}
function Navbar(){const [open,setOpen]=useState(false); return <header className="nav"><Logo/><nav className="desktop">{nav.map(([t,h])=><a key={t} href={h}>{t}</a>)}<a className="btn small" href="/#contact">Book a Free Consultation</a></nav><button className="hamb" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<span>×</span>:<span>☰</span>}</button>{open&&<div className="mobile">{nav.map(([t,h])=><a key={t} onClick={()=>setOpen(false)} href={h}>{t}</a>)}<a className="btn" onClick={()=>setOpen(false)} href="/#contact">Book a Free Consultation</a></div>}</header>}
function Hero(){const nodes=['New Lead','AI Assistant','CRM','WhatsApp','AI Call','Appointment Booked'];return <section id="home" className="hero section"><div className="heroCopy"><p className="eyebrow">AI automation systems for service businesses</p><h1>Build a Business That Works Smarter With AI</h1><p className="lead">Autonestix designs intelligent automation systems that connect your website, customer conversations, lead management, WhatsApp, AI calling and appointment booking — helping your business operate more efficiently.</p><div className="actions"><a className="btn" href="/#contact">Book a Free Consultation</a><a className="btn ghost" href="/#solutions">Explore Our Solutions</a></div></div><div className="heroVisual" aria-label="Automation workflow visual">{nodes.map((n,i)=><React.Fragment key={n}><div className="flowNode"><span>{String(i+1).padStart(2,'0')}</span>{n}</div>{i<nodes.length-1&&<span className="connector">→</span>}</React.Fragment>)}</div></section>}
function Problems(){const items=['Leads waiting too long for responses','Employees manually following up with customers','Missed calls and forgotten opportunities','Manual appointment scheduling','Customer information scattered across systems','Repetitive WhatsApp and email communication'];return <section className="section split"><div><p className="eyebrow">The operational gap</p><h2>Stop Losing Time to Repetitive Work</h2><p>Your business should not depend on someone manually doing every repetitive task. Autonestix connects lead capture, conversations, follow-ups, CRM updates and booking into reliable automated workflows.</p></div><div className="checkGrid">{items.map(x=><div className="check" key={x}><span className="tick">✓</span>{x}</div>)}</div></section>}
function Services(){return <section id="solutions" className="section"><p className="eyebrow center">Solutions</p><h2 className="center">We Build AI Systems That Keep Your Business Running</h2><div className="cards">{services.map(([t,d,Icon])=><article className="card" key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
function Process(){return <section id="process" className="section"><p className="eyebrow center">How it works</p><h2 className="center">A Practical Process From Workflow to Deployment</h2><div className="timeline">{processSteps.map((s,i)=>{const [t,d]=s.split('|');return <article key={t}><b>{i+1}</b><h3>{t}</h3><p>{d}</p></article>})}</div></section>}
function Workflow(){const top=['Customer','Website','AI Chatbot','Lead Captured','CRM','Automation Engine']; const branches=['WhatsApp Follow-up','Email Follow-up','AI Voice Call']; const bottom=['Lead Qualified','Appointment Booked','Calendar','Customer Follow-up']; return <section className="section workflow"><p className="eyebrow center">Connected operations</p><h2 className="center">One Connected Business System</h2><div className="system">{top.map(x=><div className="pill" key={x}>{x}</div>)}<div className="branches">{branches.map(x=><div className="pill accent" key={x}>{x}</div>)}</div>{bottom.map(x=><div className="pill" key={x}>{x}</div>)}</div></section>}
function Industries(){return <section id="industries" className="section"><p className="eyebrow center">Industries</p><h2 className="center">Built for Local and Service-Based Businesses</h2><div className="cards industries">{industries.map(([t,d,Icon])=><article className="card" key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
function Why(){return <section className="section dark"><p className="eyebrow center">Why Autonestix</p><h2 className="center">Automation Designed Around the Complete Customer Journey</h2><div className="cards">{why.map(([t,d,Icon])=><article className="card glass" key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
function UseCase(){return <section className="section split"><div><p className="eyebrow">Use case</p><h2>See What an Automated Customer Journey Can Look Like</h2><p className="note">Automation workflows are customized based on each business's requirements and the capabilities and policies of connected platforms.</p></div><ol className="journey">{['A potential customer visits a business website.','The AI assistant answers their questions.','The customer submits their contact details.','The lead is automatically added to the CRM.','An automated WhatsApp follow-up is triggered.','An AI voice agent can follow up with the lead.','The lead selects an appointment time.','The appointment is added to the calendar.','Automated reminders and follow-ups are sent.'].map(x=><li key={x}>{x}</li>)}</ol></section>}
function About(){return <section id="about" className="section about"><p className="eyebrow">About</p><h2>Building Smarter Business Systems</h2><p>Autonestix is an AI automation business focused on helping companies connect their customer communication and operational workflows.</p><p>We design systems that combine artificial intelligence, automation and business integrations to reduce repetitive work and create more efficient processes.</p><p>Our approach starts by understanding how a business currently operates and identifying where automation can create meaningful improvements.</p></section>}
function ContactForm(){const [sent,setSent]=useState(false);function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);if(!data.getAll('automate').length){alert('Please select at least one automation area.');return} setSent(true)}return <section id="contact" className="section contact"><div><p className="eyebrow">Start here</p><h2>Ready to Automate Your Business?</h2><p>Tell us how your business currently works. We'll explore where AI and automation could help simplify your operations.</p><p><b>Email:</b> {BUSINESS.BUSINESS_EMAIL}<br/><b>Phone/WhatsApp:</b> {BUSINESS.PHONE.replaceAll('[','').replaceAll(']','')}</p></div><form onSubmit={submit}><input required name="name" placeholder="Full Name"/><input required name="business" placeholder="Business Name"/><input required type="email" name="email" placeholder="Business Email"/><input required name="phone" placeholder="Phone / WhatsApp Number"/><input required name="country" placeholder="Country"/><select required name="industry" defaultValue=""><option value="" disabled>Industry</option>{['Gym / Fitness','Clinic','Salon / Beauty','Restaurant','Real Estate','Professional Services','Local Services','Other'].map(x=><option key={x}>{x}</option>)}</select><fieldset><legend>What would you like to automate?</legend>{['Lead Generation','WhatsApp','Customer Support','AI Calling','Appointment Booking','CRM','Email','Other'].map(x=><label key={x}><input type="checkbox" name="automate" value={x}/> {x}</label>)}</fieldset><textarea required name="process" placeholder="Tell us about your current business process" rows="5"/><button className="btn" type="submit">Request a Consultation</button><small>Prepared for n8n webhook integration: {BUSINESS.N8N_WEBHOOK_URL}. No API keys are stored in this frontend.</small>{sent&&<p className="success">Thanks — your request is ready to be connected to the consultation workflow.</p>}</form></section>}
function Footer(){return <footer><Logo/><p>AI-powered automation systems for smarter business operations.</p><div>{nav.filter(([t])=>!['How It Works'].includes(t)).map(([t,h])=><a key={t} href={h}>{t}</a>)}<a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a></div><p>{BUSINESS.BUSINESS_EMAIL} · {BUSINESS.PHONE.replaceAll('[','').replaceAll(']','')}</p><p>© 2026 Autonestix. All rights reserved.</p></footer>}
function Home(){return <><Hero/><Problems/><Services/><Process/><Workflow/><Industries/><Why/><UseCase/><About/><section className="cta"><h2>Ready to Automate Your Business?</h2><p>Tell us how your business currently works. We'll explore where AI and automation could help simplify your operations.</p><a className="btn" href="/#contact">Book a Free Consultation</a><a className="btn ghost" href="/#contact">Contact Us</a></section><ContactForm/></>}
const privacy=['Information collected through contact forms may include name, business details, email, phone number, country, industry and the workflow information you choose to share.','We use enquiry information to respond to requests, understand automation requirements and communicate with prospective customers.','Autonestix may use third-party services and integrations such as CRM, email, calendar, messaging, AI and workflow automation platforms to deliver agreed services.','We take reasonable security measures, but no internet-based system can be guaranteed to be completely secure.','This website does not intentionally rely on tracking cookies. If analytics or embedded tools are added later, cookie usage should be reviewed and disclosed.','For privacy requests, contact hello.autonestix@outlook.com.']
const terms=['These Terms describe general website use and service enquiry conditions for Autonestix.','Specific services, deliverables, pricing, timelines, responsibilities and support terms are determined through individual client agreements.','Automation results depend on business processes, available data, connected third-party platforms, platform policies and user adoption. Autonestix does not guarantee revenue, sales or uninterrupted third-party service availability.','Clients are responsible for providing accurate information, required access and appropriate approvals for connected platforms.','AI and automation systems should be reviewed before production use, especially where customer communication, regulated information or operational decisions are involved.','Contact hello.autonestix@outlook.com for questions about these Terms.']
function Legal({title,items}){return <main className="section legal"><h1>{title}</h1>{items.map(x=><p key={x}>{x}</p>)}</main>}
function App(){const path=location.pathname;return <><Navbar/><main>{path==='/privacy'?<Legal title="Privacy Policy" items={privacy}/>:path==='/terms'?<Legal title="Terms of Service" items={terms}/>:<Home/>}</main><Footer/></>}
createRoot(document.getElementById('root')).render(<App />)
