import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BUSINESS } from './config/business'
import { ecosystemNodes, workflowSteps, services, problems, processSteps, industries, trustPillars, integrations, gymDemo, Icon } from './data/siteData.jsx'
import './styles.css'

const nav = [['Solutions','/#solutions'],['How It Works','/#process'],['Industries','/#industries'],['About','/#about'],['Contact','/#contact']]

function Logo(){return <a className="logo" href="/" aria-label="Autonestix home"><span className="mark">A</span><span>Autonestix</span></a>}
function Navbar(){const [open,setOpen]=useState(false); return <header className="nav"><Logo/><nav className="desktop" aria-label="Primary navigation">{nav.map(([t,h])=><a key={t} href={h}>{t}</a>)}<a className="btn small" href="/#contact">Book a Free Consultation</a></nav><button className="hamb" aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(!open)}><span>{open?'×':'☰'}</span></button>{open&&<div className="mobile">{nav.map(([t,h])=><a key={t} onClick={()=>setOpen(false)} href={h}>{t}</a>)}<a className="btn" onClick={()=>setOpen(false)} href="/#contact">Book a Free Consultation</a></div>}</header>}
function Reveal({children,className='',...props}){return <div className={`reveal ${className}`} {...props}>{children}</div>}
function ScrollReveal(){useEffect(()=>{const items=[...document.querySelectorAll('.reveal')]; const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible'); obs.unobserve(entry.target)}}),{threshold:.12}); items.forEach(item=>obs.observe(item)); return()=>obs.disconnect()},[]); return null}
function HeroVisual(){return <div className="heroVisual" aria-label="AI business automation ecosystem"><div className="orbit"><div className="core"><span>Autonestix</span><strong>AI Operating System</strong></div>{ecosystemNodes.map((node,i)=><div className={`orbitNode n${i+1}`} key={node}><span />{node}</div>)}<svg viewBox="0 0 520 520" aria-hidden="true"><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#57f4d2"/><stop offset="1" stopColor="#8bb7ff"/></linearGradient></defs>{ecosystemNodes.map((_,i)=><line key={i} x1="260" y1="260" x2={260+205*Math.cos((i/ecosystemNodes.length)*Math.PI*2-Math.PI/2)} y2={260+205*Math.sin((i/ecosystemNodes.length)*Math.PI*2-Math.PI/2)} />)}<circle cx="260" cy="260" r="203" /></svg></div></div>}
function Hero(){return <section id="home" className="hero section"><Reveal className="heroCopy"><p className="eyebrow">AI automation agency for local and service businesses</p><h1>AI Systems That Run Your Business 24/7</h1><p className="lead">Autonestix builds intelligent automation systems that capture leads, answer customers, make AI calls, automate follow-ups and book appointments automatically.</p><div className="actions"><a className="btn" href="/#contact">Book a Free Automation Consultation</a><a className="btn ghost" href="/#solutions">Explore Our AI Systems</a></div><div className="signal"><span>Website</span><b>→</b><span>AI Chatbot</span><b>→</b><span>CRM</span><b>→</b><span>Appointment</span></div></Reveal><Reveal><HeroVisual/></Reveal></section>}
function Problems(){return <section className="section split"><Reveal><p className="eyebrow">The business problem</p><h2>Manual operations quietly leak revenue every day.</h2><p>Missed calls, slow replies and scattered lead details create friction. Autonestix replaces disconnected manual tasks with one responsive automation layer.</p><div className="solutionBox"><strong>Autonestix connects the full journey:</strong><span>Website → AI Chatbot → Lead Capture → CRM → Automated Workflow → AI Voice Agent → Appointment Booking → Calendar → Customer Follow-Up</span></div></Reveal><Reveal className="problemGrid">{problems.map(([t,d])=><article className="problem" key={t}><Icon>!</Icon><h3>{t}</h3><p>{d}</p></article>)}</Reveal></section>}
function Workflow(){return <section className="section workflow"><Reveal><p className="eyebrow center">Automation workflow</p><h2 className="center">A visual pipeline from first visit to booked appointment.</h2><div className="pipeline">{workflowSteps.map((step,i)=><article className="pipeStep" key={step} style={{'--i':i}}><span>{String(i+1).padStart(2,'0')}</span><strong>{step}</strong>{i<workflowSteps.length-1&&<i aria-hidden="true" />}</article>)}</div></Reveal></section>}
function Services(){return <section id="solutions" className="section"><Reveal><p className="eyebrow center">Solutions</p><h2 className="center">Premium AI automation systems for customer communication, sales and operations.</h2><div className="cards">{services.map(([t,d,icon])=><article className="card" key={t}><Icon>{icon}</Icon><h3>{t}</h3><p>{d}</p></article>)}</div></Reveal></section>}
function Process(){return <section id="process" className="section process"><Reveal><p className="eyebrow center">How it works</p><h2 className="center">A clear implementation process from discovery to scale.</h2><div className="timeline">{processSteps.map(([t,d],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{d}</p></article>)}</div></Reveal></section>}
function Industries(){return <section id="industries" className="section"><Reveal><p className="eyebrow center">Industries</p><h2 className="center">Built for local businesses where speed, follow-up and booking matter.</h2><div className="cards industries">{industries.map(([t,d,icon])=><article className="card industry" key={t}><Icon>{icon}</Icon><h3>{t}</h3><p>{d}</p></article>)}</div></Reveal></section>}
function Trust(){return <section id="about" className="section trust"><Reveal><p className="eyebrow center">Built Around Your Business</p><h2 className="center">High-trust automation without fake logos, inflated claims or black-box promises.</h2><div className="trustGrid">{trustPillars.map(([t,d])=><article key={t}><span>✓</span><h3>{t}</h3><p>{d}</p></article>)}</div></Reveal></section>}
function Integrations(){return <section className="section integrations"><Reveal><p className="eyebrow center">Technology & integrations</p><h2 className="center">Connect the platforms your business already depends on.</h2><div className="integrationCloud">{integrations.map(x=><span key={x}>{x}</span>)}</div><p className="center muted">Integration availability depends on each platform's API access, permissions and policies. No official partnerships are implied.</p></Reveal></section>}
function Demo(){return <section className="section demo"><Reveal><div><p className="eyebrow">See AI Automation in Action</p><h2>Gym Lead Automation</h2><p>Here is a realistic example of how a fitness business can turn a website inquiry into a qualified, booked and reminded appointment without manual chasing.</p></div><div className="demoFlow">{gymDemo.map((x,i)=><article key={x}><span>{i+1}</span>{x}</article>)}</div></Reveal></section>}
function ContactForm(){const [sent,setSent]=useState(false);function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);if(!data.get('automate')){alert('Please describe what you would like to automate.');return} setSent(true)}return <section id="contact" className="section contact"><Reveal><p className="eyebrow">Start here</p><h2>Ready to Automate Your Business?</h2><p>Let's identify the repetitive tasks slowing down your business and build an AI system that handles them automatically.</p><p><b>Email:</b> {BUSINESS.BUSINESS_EMAIL}<br/><b>Phone/WhatsApp:</b> {BUSINESS.PHONE.replaceAll('[','').replaceAll(']','')}</p></Reveal><Reveal><form onSubmit={submit}><input required name="name" placeholder="Name"/><input required name="business" placeholder="Business Name"/><input required type="email" name="email" placeholder="Email"/><input required name="phone" placeholder="Phone"/><select required name="businessType" defaultValue=""><option value="" disabled>Business Type</option>{['Gym / Fitness','Clinic','Salon','Restaurant','Real Estate','Service Business','Other Local Business'].map(x=><option key={x}>{x}</option>)}</select><input required name="automate" placeholder="What would you like to automate?"/><textarea required name="message" placeholder="Message" rows="5"/><button className="btn" type="submit">Book Your Free Automation Consultation</button><small>Configurable n8n webhook placeholder preserved: {BUSINESS.N8N_WEBHOOK_URL}. This frontend does not store API keys.</small>{sent&&<p className="success">Thanks — your request is ready to be connected to the consultation workflow.</p>}</form></Reveal></section>}
function Footer(){return <footer><Logo/><p>AI-powered automation systems for smarter business operations.</p><div>{nav.map(([t,h])=><a key={t} href={h}>{t}</a>)}<a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a></div><p>{BUSINESS.BUSINESS_EMAIL} · {BUSINESS.PHONE.replaceAll('[','').replaceAll(']','')}</p><p>© 2026 Autonestix. All rights reserved.</p></footer>}
function Home(){return <><Hero/><Problems/><Workflow/><Services/><Process/><Industries/><Trust/><Integrations/><Demo/><section className="cta"><h2>Ready to Automate Your Business?</h2><p>Let's identify the repetitive tasks slowing down your business and build an AI system that handles them automatically.</p><a className="btn" href="/#contact">Book Your Free Automation Consultation</a></section><ContactForm/></>}
const privacy=['Information collected through contact forms may include name, business details, email, phone number, business type and the workflow information you choose to share.','We use enquiry information to respond to requests, understand automation requirements and communicate with prospective customers.','Autonestix may use third-party services and integrations such as CRM, email, calendar, messaging, AI and workflow automation platforms to deliver agreed services.','We take reasonable security measures, but no internet-based system can be guaranteed to be completely secure.','This website does not intentionally rely on tracking cookies. If analytics or embedded tools are added later, cookie usage should be reviewed and disclosed.','For privacy requests, contact hello.autonestix@outlook.com.']
const terms=['These Terms describe general website use and service enquiry conditions for Autonestix.','Specific services, deliverables, pricing, timelines, responsibilities and support terms are determined through individual client agreements.','Automation results depend on business processes, available data, connected third-party platforms, platform policies and user adoption. Autonestix does not guarantee revenue, sales or uninterrupted third-party service availability.','Clients are responsible for providing accurate information, required access and appropriate approvals for connected platforms.','AI and automation systems should be reviewed before production use, especially where customer communication, regulated information or operational decisions are involved.','Contact hello.autonestix@outlook.com for questions about these Terms.']
function Legal({title,items}){return <main className="section legal"><h1>{title}</h1>{items.map(x=><p key={x}>{x}</p>)}</main>}
function App(){const path=location.pathname;return <><ScrollReveal/><Navbar/><main>{path==='/privacy'?<Legal title="Privacy Policy" items={privacy}/>:path==='/terms'?<Legal title="Terms of Service" items={terms}/>:<Home/>}</main><Footer/></>}
createRoot(document.getElementById('root')).render(<App />)
